name: Web Tests - SauceDemo

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Chrome e dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          # Instala dependências adicionais para headless
          sudo apt-get install -y xvfb libxi6 libgconf-2-4
          google-chrome --version

      - name: Instalar Python dependencies
        run: |
          pip install --upgrade pip
          pip install selenium pytest faker webdriver-manager

      - name: Rodar testes
        working-directory: ./Teste_E2E
        env:
          HEADLESS: "true"
        run: pytest tests/test_e2e_purchase.py -v --tb=short